### ISSUE TITLE
German Bible

### ISSUE THREAD

**Issue by matthiasjager** [Slipity/App#11]
Is it possible to add a German Bible translation?

**Comment by josiaho** [comment]
Sure thing! I get most of my translations from [https://getbible.net](https://getbible.net).

They list:
Elberfelder 1871
Elberfelder 1905
Luther 1545
Luther 1912

Would one of those work?

**Comment by matthiasjager** [comment]
These are all quite old translations. Out of these four, Luther 1912 would be the best choice. That one will still be useable. Better than none for sure :) Thanks a lot!

**Comment by josiaho** [comment]
Sure! Or if you know of a better translation in json or XML format I could work with that too?
