### ISSUE TITLE
Background Video Issue

### ISSUE THREAD

**Issue by DannyLFairley** [Slipity/App#13]
Hello! I absolutely love the app! I want to thank you for even creating something so simple to solve many problems. I do, however, have an issue. When I toggle the switch that enables background videos to be looped, it does not work. Instead of the video continuing to play, it ends when the footage is done. Also, when I select a different presentation, and decide to go back into the presentation with the background video, it will not play at all. I am just inquiring to see if there is a fix in the near future for these issues. Thanks in advance!

**Comment by josiaho** [comment]
Hi Danny! I'm not able to reproduce either issue on my test devices. Which device and OS version are you using?
