### ISSUE TITLE
HDMI issue

### ISSUE THREAD

**Issue by tcorbitt20** [Slipity/App#20]
When I try using an HDMI connection from my iPad to a tv, I can’t get it to connect. What am I doing wrong?

**Comment by josiaho** [comment]
Thanks for the report - I'll check it out!

**Comment by josiaho** [comment]
Sorry for the wait, I haven't been able to reproduce this issue. Outside of Slipity does your iPad screen mirror successfully to your TV?

**Comment by tcorbitt20** [comment]
I apologize. We finally figured out the issue was a 100’ hdmi cable that is Omni directional and we had it backwards. The app works great!

**Comment by josiaho** [comment]
Haha - good to hear! 😂👍
