### ISSUE TITLE
Issue with Scripture Search

### ISSUE THREAD

**Issue by tjeakins98** [Slipity/App#22]
The scripture search bar does appear but keyboard will not open on the search, so searching for scripture is not possible on iPhone 14 pro series, not sure about other iPhones, I have uninstalled app and reset settings and still not working.

**Comment by josiaho** [comment]
Hi! Can you please check Settings > AirTurn Pedal and verify that Airturn Support is disabled?:

![image](https://user-images.githubusercontent.com/1563159/210194046-d3667b87-6591-488d-9426-931d099a1c5d.jpeg)

If so, which version of iOS are you running (i.e. 16.2)?

Thanks!

**Comment by tjeakins98** [comment]
That fixed it
