### ISSUE TITLE
Weird glitch

### ISSUE THREAD

**Issue by tcorbitt20** [Slipity/App#25]
Why is it doing this when I search for lyrics or a scripture? The app will stay looking like this until I shut it down. It was even showing previous versions of slides prior to edits when I tried to use them. It happens almost every time I use the search function. 

![IMG_0209](https://user-images.githubusercontent.com/117577987/216231072-8fe6300b-776e-44e8-869f-f8702edf6724.png)

**Comment by tcorbitt20** [comment]
And it doesn’t save any changes made or slides created while it’s acting like this.

**Comment by josiaho** [comment]
Thanks for the report! Version 1.2.17 has been submitted to the AppStore with fixes :)

**Comment by tcorbitt20** [comment]
When should it be released? Thanks!Sent from my iPadOn Feb 1, 2023, at 11:24 PM, Josiah Oslund ***@***.***> wrote:﻿
Closed #25 as completed.

**Comment by josiaho** [comment]
Typically within 24-48hrs, although it's still "Awaiting Review" at the moment...

**Comment by josiaho** [comment]
The update is (finally) available 😉

**Comment by tcorbitt20** [comment]
I don’t check this email all that often. Thank you!I have still had some issues where occasionally, slides on the right side of the screen can’t be selected. Tap on them all you want and get nothing. If you turn the iPad, sometimes it helps, sometimes not. Any ideas?Sent from my iPadOn Feb 6, 2023, at 4:19 PM, Josiah Oslund ***@***.***> wrote:﻿
The update is (finally) available 😉

**Comment by tcorbitt20** [comment]
And this keeps happening Sent from my iPadOn Feb 24, 2023, at 7:17 PM, Notasulga First Baptist ***@***.***> wrote:﻿I don’t check this email all that often. Thank you!I have still had some issues where occasionally, slides on the right side of the screen can’t be selected. Tap on them all you want and get nothing. If you turn the iPad, sometimes it helps, sometimes not. Any ideas?Sent from my iPadOn Feb 6, 2023, at 4:19 PM, Josiah Oslund ***@***.***> wrote:﻿
The update is (finally) available 😉
