### ISSUE TITLE
No ability to add backgrounds to texts

### ISSUE THREAD

**Issue by roberto-mota20** [Slipity/App#33]
The app is missing the ability to add colors as beckgrounds for texts, it is unusable whiteout it

**Comment by josiaho** [comment]
Hi Roberto! To clarify, are you looking for text "highlighting", or for an option to change the color of the screen background?

**Comment by roberto-mota20** [comment]
I'm looking for a feature that enables me to do a background on the text so it can have more contrast on diverse backgrounds

![image](https://github.com/user-attachments/assets/b2c468d4-3075-4963-ae42-3dd92a16066f)

**Comment by josiaho** [comment]
Thanks for the reference image! That should be pretty easy to add - I'll work on it this week and update you when it's headed to the AppStore. Blessings!

**Comment by roberto-mota20** [comment]
Appreciate it man

**Comment by josiaho** [comment]
Hey Roberto, The update with Text Background is live!: [https://slipity.com/new](https://slipity.com/new)
