### ISSUE TITLE
Songs from PlanningCenter are imported without line breaks.

### ISSUE THREAD

**Issue by matthiasjager** [Slipity/App#5]
Whenever I import a PCO plan, the songs show up without line breaks. I have to manually click "Quick edit text" and (without changing anything) click "Done" in order for Slipity to apply the line breaks. Thankfully, I only have to do it once for every song. But it is still an unnecessary hustle. Is there a way to fix that?

**Comment by josiaho** [comment]
@matthiasjager - I'm not able to replicate this on either of my devices - but they're both on iOS 14.0.1.

Could you let me know which Device model and iOS version you're running?

**Comment by matthiasjager** [comment]
@josiaho I am on iOS 14.0.1 on my iPhone 7. Tried the same thing with the same results on my iPad Pro (2018) on iPadOS 14.0.1.

**Comment by josiaho** [comment]
Weird - my iphone7 doesn't do that 🤔. I'll dig a little deeper - thanks for the report!

**Comment by josiaho** [comment]
@matthiasjager Any chance you could attach a sample PCO lyrics .pdf? I'm curious if my formatting in PCO makes a difference 🤷🏻‍♂️

**Comment by matthiasjager** [comment]
The song lyrics are imported into PCO from SongSelect. Here's an example:
[Oceans (Where Feet May Fail) - lyrics.pdf](https://github.com/Slipity/App/files/5438061/Oceans.Where.Feet.May.Fail.-.lyrics.pdf)

And this is what it looks like as soon as I import it into Slipity:
![IMG_0223](https://user-images.githubusercontent.com/73382680/97158632-01e27780-177a-11eb-816c-a1f4b86c79a8.png)

**Comment by josiaho** [comment]
@matthiasjager Thanks for your patience! I found and fixed the issue - thanks for your help! I've submitted the change to the AppStore (Version 1.1.3) - it's usually approved within a day or two!
