### ISSUE TITLE
App crashes and erases all your saved data

### ISSUE THREAD

**Issue by davidm7700** [Slipity/App#6]
The iOS app erases all your data all of a sudden . All your work gone. No trace  Slipity app

**Comment by josiaho** [comment]
@davidm7700 So sorry to hear about this! Do you have any steps or conditions that I can repeat to try to reproduce the issue?

**Comment by davidm7700** [comment]
Not really. The only thing I can think of is when I was adding a photo to a slide it frozen and then crashed then it seemed to reset everything 

    On Monday, November 2, 2020, 10:30:26 PM CST, Josiah Oslund <notifications@github.com> wrote:  
 
 


@davidm7700 So sorry to hear about this! Do you have any steps or conditions that I can repeat to try to reproduce the issue?

**Comment by josiaho** [comment]
@davidm7700 I've tried several variations but haven't been able to recreate the issue yet. I'll keep checking though!

**Comment by davidm7700** [comment]
Is there a way to do a backup. The app is amazing. But as off now I can trust all my work will be there for service. I would like to make a donation as well for this but just really really want to be able to trust it or at the least have a remedy incase I'm in the spot once again .! Thanks 
    On Wednesday, November 4, 2020, 11:39:59 PM CST, Josiah Oslund <notifications@github.com> wrote:  
 
 


@davidm7700 I've tried several variations but haven't been able to recreate the issue yet. I'll keep checking though!

**Comment by josiaho** [comment]
@davidm7700 There not currently a way to backup - but let me look into it. I should be able to get something together.

**Comment by josiaho** [comment]
@davidm7700 Just checking in - I'm having trouble finding a backup method that can export/import to/from the iOS Files app.

I'm looking into a cloud backup/sync option. At this point I already have some Planning Center integration built in to Slipity. Do you have a Planning Center account? The quickest route for this feature would be to use PCO as the ID (would not upload anything to PCO), and then to add other login options later (Google, Twitter, Sign In with Apple, etc).

Is this idea something that could work for you?

**Comment by kylang07** [comment]
I’ve been having this exact same issue and it’s happened on three iPads. And tonight after my church’s midweek service, it crashed again and I lost the entire library. The best I can think of, is if the app is closed with a library or playlist selected, it seems to lose all the data “sometimes.” I’ve trouble shooted this and it does not happen every time. I absolutely love the app, I just can’t trust that every time it’s opened or if someone on my sound team is using it, that all the playlists and libraries will be there. If there’s a fix that would be great!

**Comment by josiaho** [comment]
@kylang07 Thanks for the input! Can you tell if the crash tends to happen more during launch, or after it's been open a while?

**Comment by kylang07** [comment]
Sorry I’m Kyle the same guy. I thought it didn’t send with this email so I
used my work one lol

**Comment by josiaho** [comment]
@davidm7700 Would you be interested in testing a new build?

**Comment by kylang07** [comment]
Absolutely!!

**Comment by davidm7700** [comment]
heck yeah . I would like to if you go it. 

    On Friday, April 9, 2021, 01:18:14 AM CDT, Josiah Oslund ***@***.***> wrote:  
 
 


@davidm7700 Would you be interested in testing a new build?

**Comment by josiaho** [comment]
Great! Can you email me so I can add you to TestFlight? (me@josiaho.com)

Thanks!

**Comment by kylang07** [comment]
I think you already have mine. ***@***.***
