### ISSUE TITLE
Font style not working 

### ISSUE THREAD

**Issue by jzmartinez21** [Slipity/App#8]
When I click on font style. Nothing comes up

**Comment by josiaho** [comment]
Hello! I'm unable to reproduce this issue on my devices. Can you please let me know which version of iOS/iPadOS you're running?

Thanks!

**Comment by jzmartinez21** [comment]
I’m running iOS 14.7.1

**Comment by josiaho** [comment]
Thanks! That's actually what I'm testing on too 🤔.

Can you verify that Slipity is up to date (at least version 1.2.1)?

Here's the [AppStore link](https://apps.apple.com/us/app/slipity/id1484116483)

**Comment by jzmartinez21** [comment]
Ok. I figured out what happen. I signed into importer on my Mac and iPhone. So I make all my presentations on my back book and when they pop up on my iPhone and I try to change the font color it won’t let me.

**Comment by josiaho** [comment]
Thanks so much for the extra info - I was able to pinpoint the issue! I'm submitting the fix to the AppStore - version 1.2.3 _should_ be available within the next day or so - I'll leave this issue open until the update posts. Thanks for your help!
