### ISSUE TITLE
The slides

### ISSUE THREAD

**Issue by jzmartinez21** [Slipity/App#9]
I hooked up my iPhone through hdmi with an adapter to use Slipity. But when I’m switching through the slides it does work correctly.

**Comment by josiaho** [comment]
Thanks for the report! Do you have any further details or steps I can try to reproduce the issue? Thanks!

**Comment by jzmartinez21** [comment]
So after more research. When i copied and pasted through the importer in my MacBook and pulled it up on my iPhone it wouldn’t read right. When I copied and pasted from my phone to the app it worked fine.

**Comment by josiaho** [comment]
Was the text formatting incorrect (line breaks, etc), or are words or characters missing? Thanks!

**Comment by jzmartinez21** [comment]
I think the text was formatting incorrectly.

Have a question. Will you upload more translations of the Bible? Like NKJV or AMP?
